services:
  mysql:
    image: mysql:8.4
    container_name: portal-ita-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: portal_ita
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: portal-ita-phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8080:80"

    depends_on:
      - mysql

volumes:
  mysql_data:
